### ISSUE TITLE
same result from mean pooling?

### ISSUE THREAD

**Issue by aus70** [trodrigu/text_embeddings_elixir#1]
Hi, I tried your code (found in https://github.com/elixir-nx/bumblebee/issues/100), and the results before and after the pooling are the same, and namely:

`[0.8791295289993286, 0.5514416694641113, 0.5670843720436096, 0.4868759512901306]`

Am I missing anything?

Thanks!

**Comment by trodrigu** [comment]
I think it's missing a Scholar normalize function.  Let me take a look.

**Comment by trodrigu** [comment]
I've updated the [example](https://github.com/trodrigu/text_embeddings_elixir/commit/ef82dd5a1cee9693b96ba591b087f4a9455cf74d).  I've also added the analogous python sentence transformer example for verification.
